---
dependencies: []

galaxy_info:
  role_name: common
  author: SummitEthic DevOps Team
  description: Base configuration for all SummitEthic servers
  company: SummitEthic
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - system
    - security
    - hardening
    - baseline
