# SummitEthic pre-commit hooks configuration
# This file configures automatic checks that run on git commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.14.3
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: ^roles/test/

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: ethical-check
        name: Ethical Code Check
        entry: python scripts/ethical_code_check.py
        language: python
        files: \.(py|yml|yaml|tf|sh)$
        additional_dependencies: ["pyyaml==6.0", "colorama==0.4.6"]
