---
# Malware protection tasks for SummitEthic security

- name: Install ClamAV
  package:
    name:
      - clamav
      - clamav-daemon
      - clamav-freshclam
    state: present
  register: clamav_install
  until: clamav_install is success
  retries: 3
  delay: 5
  tags: [clamav]

- name: Configure ClamAV daemon
  template:
    src: clamav/clamd.conf.j2
    dest: /etc/clamav/clamd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_clamav
  tags: [clamav]

- name: Configure ClamAV freshclam
  template:
    src: clamav/freshclam.conf.j2
    dest: /etc/clamav/freshclam.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_freshclam
  tags: [clamav]

- name: Ensure ClamAV services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - clamav-freshclam
    - clamav-daemon
  ignore_errors: true
  tags: [clamav]

- name: Configure daily ClamAV scan
  cron:
    name: "Daily ClamAV scan"
    hour: "3"
    minute: "30"
    job: "clamscan -r --quiet --infected /home /var/www /opt /etc /usr/local/bin > /var/log/clamav/daily_scan.log 2>&1"
  tags: [clamav]

- name: Ensure ClamAV log directory exists
  file:
    path: /var/log/clamav
    state: directory
    owner: clamav
    group: clamav
    mode: 0750
  tags: [clamav]

- name: Configure ClamAV log rotation
  template:
    src: clamav/clamav-logrotate.j2
    dest: /etc/logrotate.d/clamav
    owner: root
    group: root
    mode: 0644
  tags: [clamav]

- name: Install Rootkit Hunter
  package:
    name: rkhunter
    state: present
  register: rkhunter_install
  until: rkhunter_install is success
  retries: 3
  delay: 5
  tags: [rkhunter]

- name: Configure Rootkit Hunter
  template:
    src: rkhunter/rkhunter.conf.j2
    dest: /etc/rkhunter.conf
    owner: root
    group: root
    mode: 0640
  tags: [rkhunter]

- name: Update Rootkit Hunter database
  command: rkhunter --update
  changed_when: false
  tags: [rkhunter]

- name: Configure weekly Rootkit Hunter scan
  cron:
    name: "Weekly Rootkit Hunter scan"
    hour: "4"
    minute: "0"
    weekday: "0"
    job: "rkhunter --check --skip-keypress --report-warnings-only > /var/log/rkhunter/weekly_scan.log 2>&1"
  tags: [rkhunter]

- name: Ensure Rootkit Hunter log directory exists
  file:
    path: /var/log/rkhunter
    state: directory
    owner: root
    group: root
    mode: 0750
  tags: [rkhunter]

- name: Configure Rootkit Hunter log rotation
  template:
    src: rkhunter/rkhunter-logrotate.j2
    dest: /etc/logrotate.d/rkhunter
    owner: root
    group: root
    mode: 0644
  tags: [rkhunter]

- name: Install Maldet (Linux Malware Detect)
  get_url:
    url: "https://www.rfxn.com/downloads/maldetect-current.tar.gz"
    dest: "/tmp/maldetect-current.tar.gz"
    mode: 0640
  when: security_level == 'maximum' and install_maldet | bool
  tags: [maldet]

- name: Extract Maldet
  unarchive:
    src: "/tmp/maldetect-current.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: security_level == 'maximum' and install_maldet | bool
  tags: [maldet]

- name: Install Maldet
  command: /tmp/maldetect-*/install.sh
  args:
    creates: /usr/local/maldetect
  when: security_level == 'maximum' and install_maldet | bool
  tags: [maldet]

- name: Configure Maldet
  template:
    src: maldet/maldet.conf.j2
    dest: /usr/local/maldetect/conf.maldet
    owner: root
    group: root
    mode: 0640
  when: security_level == 'maximum' and install_maldet | bool
  tags: [maldet]

- name: Configure daily Maldet scan
  cron:
    name: "Daily Maldet scan"
    hour: "2"
    minute: "0"
    job: "maldet -b -r /home /var/www /tmp /opt > /dev/null 2>&1"
  when: security_level == 'maximum' and install_maldet | bool
  tags: [maldet]

- name: Configure ethical monitoring for malware detection
  template:
    src: malware-ethical-monitoring.j2
    dest: /etc/summitethic/security/malware-ethical-monitoring.conf
    owner: root
    group: root
    mode: 0640
  tags: [ethics]
