---
# Configure container logging

- name: Create log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /var/log/docker
    - /var/log/containers
  tags: [logging]

- name: Configure Docker log rotation
  template:
    src: docker-logrotate.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: 0644
  tags: [logging]

- name: Set up rsyslog Docker logging (if using syslog driver)
  template:
    src: docker-rsyslog.conf.j2
    dest: /etc/rsyslog.d/30-docker.conf
    owner: root
    group: root
    mode: 0644
  when: docker_log_driver == "syslog"
  notify: restart_rsyslog
  tags: [logging]

- name: Install log parsing tools
  package:
    name:
      - jq
      - logrotate
    state: present
  tags: [logging]

- name: Create log exploration script
  template:
    src: docker-logs.sh.j2
    dest: /usr/local/bin/docker-logs
    owner: root
    group: root
    mode: 0755
  tags: [logging]
