---
# Handlers for security role

- name: restart_ssh
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: enable_ufw
  ufw:
    state: enabled

- name: reload_iptables
  shell: iptables-restore < /etc/iptables/rules.v4
  args:
    executable: /bin/bash

- name: restart_auditd
  service:
    name: auditd
    state: restarted

- name: reload_sysctls
  command: sysctl --system

- name: reload_pam
  command: pam-auth-update --package
  args:
    warn: false

- name: restart_aide
  service:
    name: aide
    state: restarted
  when: ansible_service_mgr == "systemd" and aide_enabled
