---
# Docker user configuration

- name: Check if Docker group exists
  getent:
    database: group
    key: docker
  register: docker_group_exists
  tags: [docker]

- name: Add users to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  when: docker_group_exists.rc == 0
  tags: [docker]

- name: Create Docker configuration directory
  file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  tags: [docker]

- name: Configure Docker CLI options
  template:
    src: docker_config.j2
    dest: "/home/{{ ansible_user }}/.docker/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  tags: [docker]

- name: Set up Docker completion
  copy:
    src: docker-completion.sh
    dest: "/home/{{ ansible_user }}/.docker-completion.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  tags: [docker]

- name: Add Docker completion to bash profile
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "source ~/.docker-completion.sh"
    state: present
    create: yes
  tags: [docker]
