---
# Swap configuration

- name: Check if swap file exists
  stat:
    path: /swapfile
  register: swap_file_check
  tags: [swap]

- name: Check current swap size
  command: grep SwapTotal /proc/meminfo
  register: swap_size
  changed_when: false
  check_mode: no
  tags: [swap]

- name: Create swap file
  command: dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size_mb }}
  args:
    creates: /swapfile
  when: not swap_file_check.stat.exists
  tags: [swap]

- name: Set swap file permissions
  file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600
  when: not swap_file_check.stat.exists
  tags: [swap]

- name: Set up swap area
  command: mkswap /swapfile
  when: not swap_file_check.stat.exists
  tags: [swap]

- name: Enable swap
  command: swapon /swapfile
  when: not swap_file_check.stat.exists
  tags: [swap]

- name: Add swap to fstab
  lineinfile:
    path: /etc/fstab
    line: "/swapfile none swap sw 0 0"
    state: present
  when: not swap_file_check.stat.exists
  tags: [swap]

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
    reload: yes
  tags: [swap]

- name: Configure cache pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    reload: yes
  tags: [swap]
