---
# Initial SSH configuration

- name: Configure SSH server
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart_ssh
  tags: [ssh]

- name: Create SSH banner
  template:
    src: issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh
  tags: [ssh, banner]

- name: Ensure SSH host keys are secure
  command: >
    ssh-keygen -A
  args:
    creates: /etc/ssh/ssh_host_ed25519_key
  notify: restart_ssh
  changed_when: false
  tags: [ssh, security]
