---
# Common role standard variables

# System configuration
common_locale_gen:
  - "{{ common_locale }}"
  - "en_US.UTF-8"

# NTP configuration
ntp_timezone: "{{ common_timezone }}"
ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"

# System optimization parameters
sysctl_settings:
  # Network optimization
  - name: net.ipv4.tcp_fin_timeout
    value: 20
  - name: net.ipv4.tcp_keepalive_time
    value: 1200
  - name: net.ipv4.tcp_max_syn_backlog
    value: 4096
  - name: net.ipv4.tcp_syncookies
    value: 1
  - name: net.ipv4.ip_local_port_range
    value: "1024 65000"
  # Security hardening
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.all.log_martians
    value: 1
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv6.conf.all.accept_redirects
    value: 0
  - name: net.ipv6.conf.all.accept_source_route
    value: 0
  # Kernel hardening
  - name: kernel.randomize_va_space
    value: 2
  - name: kernel.kptr_restrict
    value: 1
  - name: kernel.dmesg_restrict
    value: 1
  - name: fs.protected_hardlinks
    value: 1
  - name: fs.protected_symlinks
    value: 1

# Resource limits
resource_limits:
  - domain: "*"
    type: soft
    item: nofile
    value: 65536
  - domain: "*"
    type: hard
    item: nofile
    value: 65536
  - domain: "*"
    type: soft
    item: nproc
    value: 10240
  - domain: "*"
    type: hard
    item: nproc
    value: 10240
