name: Ansible Lint

on:
  push:
    branches: [main]
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-lint.yml"

jobs:
  lint:
    name: Lint Ansible Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllint

      - name: Detect modified files
        id: changed-files
        if: github.event_name == 'pull_request'
        run: |
          ansible_files=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -E '^ansible/.*\.(yml|yaml)$' || echo "")
          echo "::set-output name=files::$ansible_files"

      - name: Lint modified Ansible files
        if: github.event_name == 'pull_request' && steps.changed-files.outputs.files != ''
        run: |
          ansible-lint ${{ steps.changed-files.outputs.files }} -v

      - name: Lint all Ansible files
        if: github.event_name != 'pull_request'
        run: |
          ansible-lint ansible/ -v

      - name: YAML Lint
        run: |
          yamllint -c .yamllint ansible/

      - name: Ethical Practices Check
        run: |
          echo "Checking for ethical considerations in Ansible code..."
          grep -r "org.summitethic" ansible/ || echo "Warning: No ethical tags found in code"
          grep -r "ethical" ansible/ || echo "Warning: No explicit ethical considerations found"

      - name: Security Practices Check
        run: |
          echo "Checking for security best practices in Ansible code..."
          # Check for plain text passwords
          ! grep -r "password:" --include="*.yml" --include="*.yaml" ansible/ | grep -v "vault" || echo "Warning: Possible plain text passwords found"
          # Check for proper use of no_log
          grep -r "no_log: true" --include="*.yml" --include="*.yaml" ansible/ || echo "Warning: Limited use of no_log for sensitive tasks"
