name: Molecule Tests

on:
  push:
    branches: [main]
    paths:
      - "ansible/roles/**"
      - ".github/workflows/molecule-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "ansible/roles/**"
      - ".github/workflows/molecule-tests.yml"

jobs:
  test:
    name: Run Molecule Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2204
          - debian11
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-docker pytest-testinfra docker

      - name: Find changed roles
        id: changed-roles
        if: github.event_name == 'pull_request'
        run: |
          changed_roles=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep -E '^ansible/roles/[^/]+/' | cut -d/ -f3 | sort -u || echo "")
          echo "::set-output name=roles::$changed_roles"

      - name: Run Molecule tests on changed roles
        if: github.event_name == 'pull_request' && steps.changed-roles.outputs.roles != ''
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          cd ansible
          for role in ${{ steps.changed-roles.outputs.roles }}; do
            if [ -d "roles/$role/molecule" ]; then
              cd roles/$role
              molecule test
              cd ../..
            else
              echo "No molecule tests found for role: $role"
            fi
          done

      - name: Run Molecule tests on core roles
        if: github.event_name != 'pull_request'
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          cd ansible
          for role in roles/core/*; do
            if [ -d "$role/molecule" ]; then
              cd $role
              molecule test
              cd ../../..
            fi
          done

      - name: Run Molecule tests on service roles
        if: github.event_name != 'pull_request'
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          cd ansible
          for role in roles/services/*; do
            if [ -d "$role/molecule" ]; then
              cd $role
              molecule test
              cd ../../..
            fi
          done
